version: "3.8"
services:
  app:
    build: .
    ports:
      - 3000:3003
    working_dir: /app
    volumes: 
      - ./:/app
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   depends_on:
  #     - pg
  # pg:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
