version: "3.8"
services:
  app:
    build: .
    working_dir: /myapp
    volumes: 
      - ./:/myapp
    ports:
      - 3000:3000
    depends_on:
      - front
  front: 
    tty: true
    working_dir: /myapp
    volumes: 
      - ./:/myapp
    build:
      context: .
      dockerfile: ./Dockerfile-front
    image: node
